apiVersion: v1
kind: Pod

metadata:
  name: todo-app-pod
  labels:
    app: todo-app

spec:
  imagePullSecrets:
    - name: ecr-secret

  containers:
    - name: todo-app
      image: IMAGE_PLACEHOLDER
      ports:
        - containerPort: 80
